name: xtiles-snap
base: core22
version: "__VERSION__"
summary: xTiles application for Linux
description: |
  Unofficial xTiles application for Linux

grade: stable
confinement: strict
icon: snap/gui/icon.png

architectures:
  - build-on: __ARCH__

apps:
  xtiles-snap:
    command: xtiles-snap --no-sandbox
    desktop: usr/share/applications/xtiles-snap.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - audio-playback
      - audio-record
      - camera
      - home
      - removable-media
      - opengl

parts:
  xtiles-snap:
    plugin: dump
    source: app
    stage-packages:
      - libnss3
      - libatk-bridge2.0-0
      - libdrm2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libatspi2.0-0
      - libgtk-3-0
