name: xtiles-snap
base: core22
version: "1.0.3"
summary: xTiles application for Linux
description: |
  Unofficial xTiles application for Linux

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  xtiles-snap:
    command: xtiles-snap
    desktop: usr/share/applications/xtiles-snap.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - audio-playback
      - audio-record
      - camera
      - home
      - removable-media
      - opengl

parts:
  xtiles-snap:
    plugin: nil
    source: .
    build-packages:
      - curl
      - build-essential
      - libnss3-dev
      - libatk-bridge2.0-dev
      - libdrm-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxrandr-dev
      - libgbm-dev
      - libxss-dev
      - libasound2-dev
      - libgtk-3-dev
    stage-packages:
      - libnss3
      - libatk-bridge2.0-0
      - libdrm2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libatspi2.0-0
      - libgtk-3-0
    override-build: |
      # Determine architecture
      ARCH=$(uname -m)
      if [ "$ARCH" = "aarch64" ]; then
        NODE_ARCH="arm64"
      else
        NODE_ARCH="x64"
      fi
      NODE_VERSION="22.14.0"
      CACHE_DIR="$SNAPCRAFT_PART_BUILD/../cache"
      mkdir -p "$CACHE_DIR"
      NODE_TARBALL="node-v${NODE_VERSION}-linux-${NODE_ARCH}.tar.gz"
      if [ ! -f "$CACHE_DIR/$NODE_TARBALL" ]; then
        curl --retry 5 -s "https://nodejs.org/dist/v${NODE_VERSION}/$NODE_TARBALL" \
          -o "$CACHE_DIR/$NODE_TARBALL"
      fi
      tar -xzf "$CACHE_DIR/$NODE_TARBALL" -C /usr/local --strip-components=1

      # Install dependencies (including devDependencies)
      npm install

      # Build the Electron app (electron-builder is in node_modules/.bin)
      npx electron-builder --linux snap

      # Stage the unpacked app
      mkdir -p "$SNAPCRAFT_PART_INSTALL"
      cp -r dist/linux-*unpacked/* "$SNAPCRAFT_PART_INSTALL/"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/usr/share/applications"
      cp xtiles-snap.desktop "$SNAPCRAFT_PART_INSTALL/usr/share/applications/"
    organize:
      "resources/app.asar": "resources/app.asar"
      "xtiles-snap": "xtiles-snap"
