name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Snap and DEB (${{ matrix.arch }})
        run: |
          npx electron-builder --linux snap --${{ matrix.arch }}
          npx electron-builder --linux deb --${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release Notes
        if: matrix.arch == 'x64' # Solo extraer una vez
        id: release_notes
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_VERSION#v}
          awk "/^## \[$VERSION\]/{p=1; next} /^## \[/{p=0} p" CHANGELOG.md > release_notes.md
          cat release_notes.md

      - name: Upload to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: dist/*.snap
          release: stable

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release_notes.md
          files: |
            dist/*.deb
            dist/*.snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
