name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Linting (ESLint)
        run: npm run lint

      - name: Build Test (DEB)
        run: npx electron-builder --linux deb --x64 --publish never
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test
